variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

stages:
  - test
  - package

crlf_test:
  stage: test
  image: alpine:3.10
  only:
    - merge_requests
  script:
    - apk add --no-cache bash file
    - chmod +x ./ci/test_crlf.sh
    - ./ci/test_crlf.sh

flake8:
  stage: test
  image: python:3.6-slim-stretch
  only:
    - merge_requests
  script:
    - chmod +x ./ci/test_flake8.sh
    - ./ci/test_flake8.sh

unit_tests:
  stage: test
  image: python:3.6-slim-stretch
  only:
    - merge_requests
  script:
    - chmod +x ./ci/test_unit_tests.sh
    - ./ci/test_unit_tests.sh

docker_test:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - merge_requests
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push 

deploy:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
    - master
