image: python:3.6-slim-stretch

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

before_script:
  - python -V

flake8:
  script:
    - python -m pip install flake8
    - python -m flake8 --config=./src/.flake8

unit_tests:
  script:
    - cd ./src
    - python -m pip install pipenv
    - python -m pipenv sync
    - python -m pipenv run python -m unittest
