image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V

flake8:
  script:
    - python -m pip install flake8
    - python -m flake8

unit_tests:
  script:
    - python tests.py
